In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3]

In [3]:
type(lst)

list

In [4]:
np.array(lst)

array([1, 2, 3])

In [5]:
lst

[1, 2, 3]

In [6]:
basic_array = np.array(lst)

In [7]:
basic_array

array([1, 2, 3])

In [10]:
basic_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np_matrix = np.array(basic_matrix)

In [13]:
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])